image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

before_script:
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./creds
  - echo $GCR_ACCOUNT_CREDS | base64 -d > ./key.json
  - export TF_VAR_cloudflare_api_key=$CLOUDFLARE_API_KEY
  - export TF_VAR_mysql_root_pass=$MYSQL_ROOT_PASSWORD
  - terraform init
stages:
  - validate
  - plan
  - apply
validate:
  stage: validate
  script:
    - terraform validate
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
